# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_remove_tag_post'),
        ('posts', '0002_auto_20170903_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
